### ISSUE TITLE
spacing in notification titles

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#47] opened 2020-10-11 11:00 UTC
followed you46 minutes ago

liked yourpost 2 hours ago

replied to yourpost 4 hours ago

replied in a discussion you're in4 hours ago

liked yourpost 1000 sats8 hours ago

**Comment by Real-FEELS** [comment] 2020-10-11 16:20
Fixed with `plaintext` class 👍👍👍👍

duplicate of #46

**Closed as completed by Real-FEELS** 2020-10-11 16:20 UTC
