### ISSUE TITLE
Still got newlines following links in posts

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/FeelsTheme#2] opened 2020-08-29 23:45 UTC

**Comment by Real-FEELS** [comment] 2020-09-01 10:45
Please provide CSS fix you used

**Comment by Real-FEELS** [comment] 2020-09-01 11:01
is this a dupe of #4 ?

**Comment by Real-FEELS** [comment] 2020-09-01 11:03
Post text should be inside paragraph tag. Please make the changes to the HTML/JS
Then I will be able to target a post with only `<a>link</a>` or a post with `<p>text <a>link</a></p>`

**Comment by FreeTrade** [comment] 2020-09-02 02:28
ok paragraph tags added.

Also, have allowed newlines in general in posts, making them more like twitter posts, less like reddit headlines.

**Comment by Real-FEELS** [comment] 2020-09-02 07:53
Should be fixed with latest PR

**Closed as completed by Real-FEELS** 2020-09-02 07:53 UTC
